version: 2.0

jobs:
  bulid:
    machine: true
    steps:
      - checkout
      - run: 
        command: npm test


workflows:
  version: 2
  build-deploy:
  jobs:
    build:
      branches:
        only:
          - master
          - /rc-.*/